# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb7750fc8b23a2a6b5e2cf22fbb49b26ad9db37debfe9888cbb9444f5297523386acfd4902a45bf5c74eeefd5d4b21d9dc6f0de30f783112caaa80f99676cfb1

test:
  secret_key_base: 5d938a30290e4c1b6fa04fe2954991324a9973292d8d3d008ff9d3eea01ec4b97f5f0a0a2647564260a92e14697f228addf84b13f8f5e66f1146e78ef8d94900

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
